---
- name: Stop the blockchain node service .......... {{ blockchain_node_user }}{{ '%03d' | format(node_num) }}.
  ansible.builtin.systemd_service:
    name: "{{ blockchain_node_company }}{{ '%03d' | format(node_num) }}"
    daemon_reload: true
    state: stopped
  register: blockchain_node_stop_service
  failed_when:
    - blockchain_node_stop_service.failed == true
    - '"Could not find the requested service" not in blockchain_node_stop_service.msg'

- name: Remove the blockchain node service.
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ blockchain_node_company }}{{ '%03d' | format(node_num) }}.service"
    state: absent

- name: Remove user accounts.
  ansible.builtin.user:
    name: "{{ blockchain_node_user }}{{ '%03d' | format(node_num) }}"
    remove: true
    state: absent
